# ==== Override jump sizes ====
[[mgr.prepend_keymap]]
desc = "Move cursor down"
on = "<C-d>"
run = "arrow 5"

[[mgr.prepend_keymap]]
desc = "Move cursor up"
on = "<C-u>"
run = "arrow -5"

# Scroll
[[mgr.prepend_keymap]]
desc = "Scroll down"
on = "<C-f>"
run = "arrow 50%"

[[mgr.prepend_keymap]]
desc = "Scroll up"
on = "<C-b>"
run = "arrow -50%"


# ==== Other locations ====
[[mgr.prepend_keymap]]
desc = "Cd to ~/uni"
on   = [ "g", "u" ]
run  = "cd ~/uni"

[[mgr.prepend_keymap]]
desc = "Cd to ~/prog"
on   = [ "g", "p" ]
run  = "cd ~/prog"

[[mgr.prepend_keymap]]
desc = "Cd to config"
on   = [ "g", "." ]
run  = "cd ~/config"

[[mgr.prepend_keymap]]
desc = "Cd to archive"
on   = [ "g", "a" ]
run  = "cd ~/archive"

# ==== Other navigations ====
[[mgr.prepend_keymap]]
desc = "Cd to git root"
on   = [ "g", "r" ]
for  = "unix"
run  = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'

[[mgr.prepend_keymap]]
desc = "Open $SHELL here"
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'

