# ==== Other locations ====
[[mgr.prepend_keymap]]
desc = "Cd to ~/Uni"
on   = [ "g", "u" ]
run  = "cd ~/Uni"

[[mgr.prepend_keymap]]
desc = "Cd to dotfiles"
on   = [ "g", "." ]
run  = "cd ~/Prog/dotfiles"

[[mgr.prepend_keymap]]
desc = "Cd to magnofiles"
on   = [ "g", "m" ]
run  = "cd /media/magno/magnofiles/"

# ==== Other navigations ====
[[mgr.prepend_keymap]]
desc = "Cd to git root"
on   = [ "g", "r" ]
for  = "unix"
run  = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'

[[mgr.prepend_keymap]]
desc = "Open $SHELL here"
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'

